[package]
name = "advent_of_code2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matches = { version = "0.1.10", features = [] }
num = "0.4.1"
log = "0.4.20"
